# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 20ce3640548f0cb8ea178800617e01480a81aef4d85c8d0f6f6e5c6f7f52ba6a4d5b841edec8552be6a04ca71afd1e34809ffd390ab5475744a73581396259dc

test:
  secret_key_base: 92e8992057ef1e94a2a1d068b4fc9cb14650e3df05f0c38860d1a8da9edd69f6544e166cbad0cfd9ae0f05a7a36287c7001f74d57e1da2d41214babc0ecb7e8a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
